### ISSUE TITLE
Add Solid Model

### ISSUE THREAD

**Issue by roosre** [ansys/pyacp#441]
### 📝 Description of the feature

Add tree object for Solid Model

Note: discuss how to handle imported materials with UUID from solid model CDB export and / or "save APDL commands"
See this PR
https://tfs.ansys.com:8443/tfs/ANSYS_Development/ANSYS-CH/_git/acp/pullrequest/460928

**Comment by greschd** [comment]
Note: should also include the solid model export functionality.
