### ISSUE TITLE
Review module structure and class names

### ISSUE THREAD

**Issue by greschd** [ansys/pyacp#637]
Since we are preparing for a "full" release, now is the chance to once again review the module structure and / or class and method names.

In particular, we should review the class names added since the last beta release.

I would tend to think some of the enum class names could use being made a bit more specific.

**Comment by roosre** [comment]
@greschd , here are my inputs

Proposed changes
- [ ] UnitType instead of DimensionType
- [ ] Unify names: should we use Cutoff or CutOff, Dropoff or DropOff. My proposal is CutOff and DropOff...

Other remarks
- [ ] Remove ConnectLaunchConfig from ansys.acp.core?
