### ISSUE TITLE
Add compatibility / upgrade page

### ISSUE THREAD

**Issue by greschd** [ansys/pyacp#724]
See

> What do you think about adding a compatibility section like the one at the bottom of this page in [DPF Composites](https://composites.dpf.docs.pyansys.com/version/stable/intro.html)? Or at least a section which informs the customers that 2025 R1 is needed to run all features. I couldn't find any reference to minimum version of the unified installer.

_Originally posted by @roosre in https://github.com/ansys/pyacp/pull/709#pullrequestreview-2469866612_

> Yes, I think we should do that. The individual classes have a note 
>
>> Added in ACP server version XYZ.
>
> in their API reference, but it would make sense to collect that information onto one page.
>
> I was also considering adding some description of how to upgrade from the beta version to the full release. While it was explicitly stated in the beta note that the API may change, I think we should still give a brief overview of changes and how to migrate the code.

_Originally posted by @greschd in https://github.com/ansys/pyacp/issues/709#issuecomment-2507835883_

**Comment by roosre** [comment]
I would add a section Compatibility under [user guide](https://acp.docs.pyansys.com/version/dev/user_guide/index.html).
I am not sure if we have to list all the details there but at least guide the user to where the information is available (API documentation).

There are quite many API changes: removal of ACPWorkflow, renamings, clean up of the module structure, etc. Depending on the changes, we can provide all details or list the most important changes only.
