### ISSUE TITLE
Opening acph5 file using a plain path fails

### ISSUE THREAD

**Issue by SRaimondi** [ansys/pyacp#739]
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### 🐞 Description of the bug

Trying to open a simple model by passing a path that is written using `""` or `''` generates an error with the following traceback
`Traceback (most recent call last):
  File "D:\ANSYSDev\pyacp_venv\lib\site-packages\ansys\acp\core\_tree_objects\_grpc_helpers\exceptions.py", line 55, in wrap_grpc_errors
    yield
  File "D:\ANSYSDev\pyacp_venv\lib\site-packages\ansys\acp\core\_tree_objects\model.py", line 331, in _from_file
    reply = model_pb2_grpc.ObjectServiceStub(server_wrapper.channel).LoadFromFile(request)
  File "D:\ANSYSDev\pyacp_venv\lib\site-packages\grpc\_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "D:\ANSYSDev\pyacp_venv\lib\site-packages\grpc\_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unknown error: Failed to load ACP model from acph5 file: Error: H5Fopen failed
"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Unknown error: Failed to load ACP model from acph5 file: Error: H5Fopen failed\n", grpc_status:2, created_time:"2024-12-10T07:03:33.1308968+00:00"}"`

### 📝 Steps to reproduce

Follow the instructions from the PyACP [Getting Started](https://acp.docs.pyansys.com/version/dev/intro.html#getting-started) page up to the [Get a Model](https://acp.docs.pyansys.com/version/dev/intro.html#get-a-model) section. At this point, try to load a model from the `acp_test_model_data` as either `model = acp.import_model('D:\ANSYSDev\acp_test_model_data\model_data\acp\simple_plate.acph5')` or `model = acp.import_model("D:\ANSYSDev\acp_test_model_data\model_data\acp\simple_plate.acph5")`, this will generate the above error. 
Notice that using a raw string as path, `model = acp.import_model(r'D:\ANSYSDev\acp_test_model_data\model_data\acp\simple_plate.acph5')`, does work as expected, same as `model = acp.import_model('D:\\ANSYSDev\\acp_test_model_data\\model_data\\acp\\simple_plate.acph5')`.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

ANSYS suite 2025 R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
aiohappyeyeballs==2.4.4
aiohttp==3.11.9
aiosignal==1.3.1
ansys-acp-core==0.1rc1
ansys-api-acp==0.2.0
ansys-api-mapdl==0.5.2
ansys-api-mechanical==0.1.2
ansys-api-platform-instancemanagement==1.1.0
ansys-api-tools-filetransfer==0.1.1
ansys-dpf-composites==0.6.1
ansys-dpf-core==0.13.3
ansys-mapdl-core==0.68.6
ansys-mapdl-reader==0.54.2
ansys-math-core==0.2.0
ansys-mechanical-core==0.11.10
ansys-mechanical-env==0.1.8
ansys-mechanical-stubs==0.1.4
ansys-platform-instancemanagement==1.1.2
ansys-pythonnet==3.1.0rc4
ansys-tools-filetransfer==0.1.1
ansys-tools-local-product-launcher==0.1.1
ansys-tools-path==0.7.0
ansys-tools-visualization-interface==0.6.0
anyio==4.6.2.post1
appdirs==1.4.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==3.0.0
async-timeout==5.0.1
attrs==24.2.0
beautifulsoup4==4.12.3
bleach==6.2.0
cachetools==5.5.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
click==8.1.7
clr-loader==0.2.6
colorama==0.4.6
comm==0.2.2
contourpy==1.3.1
cycler==0.12.1
decorator==5.1.1
defusedxml==0.7.1
exceptiongroup==1.2.2
executing==2.1.0
fastjsonschema==2.21.1
fonttools==4.55.1
fqdn==1.5.1
frozenlist==1.5.0
geomdl==5.3.1
google-api-core==2.23.0
google-api-python-client==2.154.0
google-auth==2.36.0
google-auth-httplib2==0.2.0
googleapis-common-protos==1.66.0
grpcio==1.68.1
grpcio-health-checking==1.62.3
httplib2==0.22.0
idna==3.10
importlib_metadata==8.5.0
ipython==8.30.0
ipywidgets==8.1.5
isoduration==20.11.0
jedi==0.19.2
Jinja2==3.1.4
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
jupyter-events==0.10.0
jupyter_client==8.6.3
jupyter_core==5.7.2
jupyter_server==2.14.2
jupyter_server_proxy==4.4.0
jupyter_server_terminals==0.5.3
jupyterlab_pygments==0.3.0
jupyterlab_widgets==3.0.13
kiwisolver==1.4.7
MarkupSafe==3.0.2
matplotlib==3.9.3
matplotlib-inline==0.1.7
mistune==3.0.2
more-itertools==10.5.0
msgpack==1.1.0
multidict==6.1.0
nbclient==0.10.1
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
networkx==3.4.2
numpy==2.1.3
overrides==7.7.0
packaging==24.2
pandocfilters==1.5.1
parso==0.8.4
pillow==11.0.0
platformdirs==4.3.6
pooch==1.8.2
prometheus_client==0.21.1
prompt_toolkit==3.0.48
propcache==0.2.1
proto-plus==1.25.0
protobuf==4.25.5
psutil==6.1.0
pure_eval==0.2.3
pyansys-tools-versioning==0.6.0
pyasn1==0.6.1
pyasn1_modules==0.4.1
pycparser==2.22
Pygments==2.18.0
pyiges==0.3.1
pyparsing==3.2.0
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
pyvista==0.44.2
pywin32==308
pywinpty==2.0.14
PyYAML==6.0.2
pyzmq==26.2.0
referencing==0.35.1
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.22.3
rsa==4.9
scipy==1.14.1
scooby==0.10.0
Send2Trash==1.8.3
simpervisor==1.0.0
six==1.17.0
sniffio==1.3.1
soupsieve==2.6
stack-data==0.6.3
tabulate==0.9.0
terminado==0.18.1
tinycss2==1.4.0
tornado==6.4.2
tqdm==4.67.1
traitlets==5.14.3
trame==3.7.0
trame-client==3.5.0
trame-server==3.2.3
trame-vtk==2.8.12
trame-vuetify==2.7.2
types-python-dateutil==2.9.0.20241003
typing_extensions==4.12.2
uri-template==1.3.0
uritemplate==4.1.1
urllib3==2.2.3
vtk==9.3.1
wcwidth==0.2.13
webcolors==24.11.1
webencodings==0.5.1
websocket-client==1.8.0
websockets==14.1
widgetsnbextension==4.0.13
wslink==2.2.1
yarl==1.18.3
zipp==3.21.0
```

**Comment by greschd** [comment]
I think this is because the `\a` in the path is an escape sequence, so the string doesn't actually refer to the desired path:

```
>>> 'D:\ANSYSDev\acp_test_model_data\model_data\acp\simple_plate.acph5'
'D:\\ANSYSDev\x07cp_test_model_data\\model_data\x07cp\\simple_plate.acph5'
```
